---
name: Run Benchmark Suite

on:
  push:
    branches: '*'
  pull_request:
    branches:
      - $default-branch

jobs:
  build-and-run-benchmarks:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
         java-version: '11'
         distribution: 'temurin'
         architecture: 'x64'
         cache: 'maven'
      - name: Build Project
        run: make ./target/benchmarks.jar
      - name: Run Benchmarks
        run: java -jar ./target/benchmarks.jar --time-unit=ms --result-format=csv --result=benchmarks.csv
      - name: Archive Benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks.csv
          path: ./benchmarks.csv
