#+OPTIONS: toc:nil title:nil
#+TITLE: muRelBench: Artifact Submission
#+AUTHOR: Kenny Ballou
#+EMAIL: kennyballou@u.boisestate.edu
#+LINK: guix https://guix.gnu.org
#+LINK: nix https://nixos.org
#+LINK: picocli https://picocli.info/
#+LINK: jmh https://github.com/openjdk/jmh
#+LINK: artifact https://drive.google.com/file/d/1L74CfsCMotAACiVv1gUex97RkKXS2I6G/view?usp=drive_link
#+LATEX_HEADER: \usepackage[a4paper]{geometry}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage{dirtree}
#+LATEX_HEADER: \usepackage{datatool}
#+LATEX_HEADER: \usepackage{booktabs}
* muRelBench: Artifact Submission
:PROPERTIES:
:header-args:bash: :eval never :exports code
:END:

Artifact URL: [[https://drive.google.com/file/d/1L74CfsCMotAACiVv1gUex97RkKXS2I6G/view?usp=drive_link]]

After downloading the [[artifact][artifact]], please use the checksum from the abstract to
verify its validity.  As /this/ document is part of the artifact, we cannot copy
the checksum into this file.

The [[artifact][artifact]] can be unpacked using:

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
tar -zxf 6-v2.tar.gz
#+end_src

An OCI/container image is available via the ~murelbench.oci.tar.gz~ archive.

The checksum of the container image is the following:

#+NAME: CHECKSUM
#+begin_src bash :exports results :dir ./ :eval yes
sha256sum murelbench.oci.tar.gz
#+end_src

Additionally, to verify the checksum of the archives, the following command can
be used:

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
sha256sum -c murelbench.oci.tar.gz.sha256
#+end_src

If this command returns the following, then the archives have matching
checksums:

#+begin_example
murelbench.oci.tar.gz: OK
#+end_example

To load the OCI, use something similar to the following:

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
docker image load -i murelbench.oci.tar.gz
#+end_src

#+begin_quote
Under older versions of Docker, the above command may need to be adjusted:
~docker load -i ...~.
#+end_quote

The tag of the loaded container should be: ~bash-glibc-locales-benchmarks-jar:latest~.
For convenience, this can be retagged (renamed):

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
docker image tag \
       bash-glibc-locales-benchmarks-jar:latest \
       murelbench:latest
#+end_src

To execute the benchmarks within the container, the following command can be
used:

Benchmarks should execute in about an hour.

#+begin_quote
If you see question marks in the output, e.g., ~??~, it means there's an issue
with Unicode fonts and/or locality.  Adjusting the timescale can be an easy
fix, e.g., add ~--time-unit=us~ to the following command.  However, this won't
remove all ~?~ because JMH output inherently uses several Unicode characters.
#+end_quote

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
docker run -ti murelbench:latest [--time-unit=us]
#+end_src

Help options are available under the usual mechanism: ~--help~
#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
docker run -ti murelbench:latest --help
#+end_src

** Source Code and Development Environment

The source code can be found online via GitHub.
It can be cloned from the following URL:

https://github.com/BoiseState/muRelBench

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
git clone ssh://github.com/BoiseState/muRelBench.git
#+end_src

The project uses [[guix][Guix]] for project dependencies and timeless environment setup.
Guix/[[nix][Nix]] can be thought of as a ~virtualenv~ equivalent for any package or
language.  To activate, use the following:

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
guix time-machine -C channels.scm -- shell -m manifest.scm
#+end_src

In general, for evaluation, this should be unnecessary if Java version 11 and
Maven is available.  However, without Guix, a new container image cannot be
built, as this is done through ~guix pack~.

Packaging and building is accomplished via maven. Use the following command to
build a new package:

#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
mvn clean package
#+end_src

This should result in a jar file in the ~target~ directory:
~target/benchmarks.jar~.  To execute benchmarks from the built package, use the
following command:
#+attr_latex: :options basicstyle=\small\ttfamily
#+begin_src bash
java -jar target/benchmarks.jar
#+end_src

*** Outline of Source

#+begin_src bash :eval yes :exports results :results output :dir ../
tree src/main/java
#+end_src

The entry point into the project can be found in the ~Main.java~ file, under the
root package.  This uses a [[picocli][picocli]] frontend over [[jmh][JMH]], which then invokes ~jmh~
and executes the benchmarks.  Of particular interest, the
~src/main/java/edu/boisestate/mulrebench/benchmarks~ folder contains a
single benchmark class, ~OctagonClosureBench~, and a ~states~ subfolder which
contains the synthetic state objects used for benchmarks.  The synthetic states
use domains from the ~src/main/java/edu/boisestate/murelbench/domains~ folder.
Specifically, ~OctagonDifferenceBoundedMatrix~, representing octagons and the
~Constraint~ class.

* Expected Output

The expected output for the benchmarks can be found in the following table.
These results were performed on a laptop with an Intel Xeon E5-1620v4 CPU and
16GB of RAM.  For the expected output, we created a CSV file, ~benchmarks.csv~,
using the ~--result~ and ~--result-format~ options.  Finally, the output is
measured in microseconds.  We have dropped the package name and the ~count~
parameter from the output since this makes the output too large.

#+begin_src latex
\DTLloaddb{benchmarks}{benchmarks.csv}
\begin{table}[ht]
  \centering
  \caption{Expected output from \texttt{muRelBench}}
  {\tiny
  \DTLdisplaylongdb[omit={Threads,Param: count}]{benchmarks}
  }
\end{table}
#+end_src

#+begin_quote
The CSV file uses different headers than the output from the tool.  Below, we
describe the output of the framework, and in braces, the CSV headers if
different.
#+end_quote

Some explanation of the summary output is necessary to understand this output
and compare for validation.  The first column, ~Benchmark~, is the name of the
method of the benchmark.  Next, we have the parameters of the experiments, ~(N)~
{~Param: N~}, ~(count)~ {~Param: count~}, and ~(density)~ {~Param: density~}.  ~(N)~ is the
number of variables or the size of the synthetic matrices.  ~(count)~ represents
the number of constraints added to each matrix.  Finally, ~(density)~ denotes
level of "connection" between nodes within the synthetic benchmark.  More
connections lead to a "denser" matrix of values.  The next two columns report
the kind of measurement for the benchmark, ~mode~, and the number of trials for
the benchmark, ~Cnt~ {~Samples~}.  The last three columns display the "Score" of
the benchmark, ~Score~, the variation within the benchmark, ~Error~ {~Score Error
(99.9%)~}, and the units of the measured score, ~Units~.  Between the ~Score~ and
~Error~ column may be a ~?~ or a ~±~ sign, depending on locality and Unicode fonts.
At certain time scales, the value of the score may have ~??~ in the values,
usually preceded by a ~10~ and possible another ~?~.  The single ~?~ should represent
the ~≈~ symbol.  The two ~??~ are exponent of the scientific notation for the
score, typically something like ~-3~.  The error of a measure should display
within the significant digits.  At some time units, the error is below the
significant digits of the score, thus, the error is ~0~.

On the results themselves, we expect both ~chawdharyIncrementalClosure~ and
~incrementalClosure~ to demonstrate similar performance within a few 100 us/ops.
Moreover, we expect ~fullClosure~ to be orders of magnitude above the incremental
counterparts.

* Build Stuff                                                              :noexport:
:PROPERTIES:
:header-args:bash: :eval query :results none
:END:

#+begin_src bash :dir ../ :detached t
make -k package
#+end_src

#+begin_src bash
cp /gnu/store/3rbsygz3mh12mlr4d4lkxa72rpvdd4kv-bash-glibc-locales-benchmarks-jar-docker-pack.tar.gz murelbench.oci.tar.gz
#+end_src

#+begin_src bash :eval yes :exports none :results file :file murelbench.oci.tar.gz.sha256
sha256sum murelbench.oci.tar.gz
#+end_src

#+begin_src bash :detached t :results none
tar -zcf 6-v2.tar.gz README.org README.pdf benchmarks.csv murelbench.oci.tar.gz murelbench.oci.tar.gz.sha256
#+end_src

#+name: artifact-checksum
#+begin_src bash :results file :file 6-v2.tar.gz.sha256
sha256sum 6-v2.tar.gz
#+end_src

#+begin_src bash :eval yes :results none :detached t
guix shell texlive python-pygments -- latexmk -xelatex README.tex
#+end_src


# Local Variables:
# mode: org-mode
# org-latex-listings-options: (("breaklines" "true") ("firstnumber" "auto") ("frame" "single") ("numbers" "left") ("numbersep" "5pt") ("numberstyle" "\\tiny") ("showspaces" "false") ("showstringspaces" "false") ("stepnumber" "1") ("title" "\\lstname"))
# End:


#  LocalWords:  checksums frontend
